## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [1]:
import numpy as np
import pandas as pd
import scipy as sp

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [2]:
samples = np.random.normal(loc = 100, scale = 15, size = 1000)
samples

array([ 98.4896607 ,  83.45350218, 101.58148616,  71.25620735,
       114.87932552, 109.16959404,  92.69354055,  95.45610533,
        84.75824611, 101.28142097,  71.11021139,  97.07663488,
        80.60874879,  98.79439494,  86.82472196, 101.53563619,
        85.65659174, 128.74568091,  76.33918934, 106.20996825,
       114.28244877, 104.58565601,  95.41360444,  90.70757205,
       109.47640999, 101.88569735, 110.8541465 ,  88.76409105,
       105.7703377 , 101.49636378,  98.52096159,  81.32587601,
        87.17908569, 105.33262364,  98.93043141,  93.86540438,
       126.10993396, 105.48148138, 103.3006304 ,  92.9646031 ,
        99.94378828,  94.53844452,  92.76836714,  93.41784319,
        90.64216003, 124.31985798, 111.24354086, 101.4846582 ,
        94.57618084,  90.06847564, 124.09490794, 100.78226669,
       113.65952732,  93.64671964,  98.37115871,  90.73878734,
        98.55019712, 118.17100394,  85.17609991,  93.17336673,
       113.878565  ,  94.28674852, 101.30405427, 103.15509338,
        92.36238845,  99.58989104, 122.2284547 ,  86.37575595,
       100.83909233,  81.09953188,  79.98634299,  95.78651232,
       118.37960899,  93.50876884, 119.66498951,  93.2174553 ,
       127.07203396,  96.09912394,  85.60924066, 115.61334897,
        81.57218459, 110.24294325, 100.46899305, 114.95932579,
       113.33171352,  88.20052095,  99.48533112,  91.43115406,
       106.15453857,  80.06041727,  78.2634616 ,  87.78085548,
        71.96923415, 115.22663671,  95.7516211 , 117.22931412,
        95.14059911,  89.48277289,  58.47801985, 116.2034665 ,
        87.95348693, 112.27017785,  96.78541912,  89.50037451,
        92.34550656,  94.06174129, 117.88934696,  96.62326096,
       114.29509119,  96.33223549,  88.84770623,  91.38576567,
        87.07575841,  79.49691886, 100.68136242,  75.80284136,
        84.68642689,  93.76494108, 103.50196281,  93.63306419,
       117.50003844,  79.67607   ,  76.05176558, 113.05192089,
        88.7997039 , 115.1701467 , 109.93347731,  86.00152459,
       101.31463435, 112.41799726, 102.64433585, 125.72214538,
        75.79796566, 115.52262076,  93.72545033,  96.50155448,
       108.79269896, 118.59641312, 108.32851271, 107.47544374,
       123.46765129,  85.83821521,  89.56835786, 112.24321869,
        93.76792282,  95.09159292, 109.61006671,  99.978925  ,
        98.53494984, 113.51653802, 116.11001943,  97.51095502,
        90.70321559,  95.96870385,  74.29882976,  92.14855121,
        84.61725227, 113.92354178, 112.71138896, 113.71724025,
        79.38258811,  85.73784282,  63.79684603, 105.00231078,
       100.58556271,  76.32439229,  79.38119051, 101.9248062 ,
       104.93281259, 105.56858186,  92.73495952, 106.69452777,
        93.81483596, 104.51152609,  89.91138605,  90.52349072,
       114.72444578, 119.44536585,  70.70919232, 120.03106832,
        91.81650605, 113.33147077, 123.82373256, 104.51139865,
        95.06795593, 127.38266446,  96.06530852, 100.61110091,
        85.20671843,  94.69521889, 128.23576236,  89.64826607,
       115.38551431, 103.22424936,  83.76622065, 100.61338179,
        94.54574145,  91.48375537,  78.69923177, 122.66566216,
        98.73840139,  96.25415371, 112.01219458,  95.2717041 ,
        97.52509065,  76.81537313, 102.12789013,  89.73192239,
        94.17823565, 119.12059629, 115.35564261,  79.40170167,
        88.89254903, 107.05960571, 122.04348757,  82.28440264,
       120.98531053, 102.85004116,  94.55151002, 107.35899541,
       105.65907128,  98.89956301, 104.2060563 , 111.75237312,
        95.66809505,  98.31554688, 114.41303693,  88.83021136,
       103.48425597, 102.15058187,  81.66348853, 114.20471569,
        96.11407722, 101.16191115, 109.29872854, 107.11258891,
        73.35924101, 106.9284906 , 104.91123429, 100.92506491,
        81.36154644,  86.29567299,  98.35323291, 115.76070152,
        96.25511123, 107.55371265,  90.84107298, 122.81090018,
       103.94023681,  94.50175364, 115.0436286 , 120.8513105 ,
        81.73137278, 105.88033207, 114.38350161,  73.51568674,
        66.72119811, 107.60133013,  99.55418096,  80.21052424,
       108.11732724,  70.0100367 ,  89.55854202, 122.97445021,
       103.28671805,  89.3071168 ,  95.0010876 ,  86.07575507,
       112.01196066,  78.47491122,  83.442873  ,  99.10519459,
       115.98538357, 107.26885818,  91.78902165, 123.11776807,
       122.32845438, 101.39847119, 106.73428354,  70.16155741,
        94.46768775,  61.55903291,  86.79455866, 105.98178995,
        83.09475643, 105.01007808, 120.18319781,  89.92976058,
       106.24574806,  56.29881032, 107.43064453, 102.07618631,
       110.02587776, 119.07575065,  79.77899247, 136.54522838,
       136.02388815, 123.79758288,  99.48555188, 107.37532408,
       107.46405707, 113.42847027, 117.36823411, 108.2837816 ,
        94.71039994, 105.99194066,  98.80596874, 112.02895127,
       101.30172411, 140.41121721,  94.27756114, 109.69450763,
       117.51424183, 107.51051053,  76.17619678, 135.6517915 ,
       102.13368093, 131.59038954, 124.59250242,  88.93559722,
        85.76503963,  98.7438976 ,  99.78455965,  93.64389354,
       128.69436015, 109.32718116, 105.00411754,  97.78883425,
       109.24425983, 113.51957633, 100.04039379,  83.64456805,
        82.36419264,  96.56525957, 129.97448018, 117.92857868,
       109.13712617,  93.90117417, 110.72408633, 104.11767479,
        93.97025336, 107.08991562,  99.71417483,  94.21046389,
        92.47525106,  97.16374364, 107.19718215,  91.43848887,
       122.66443556,  93.10257347, 119.63813004, 104.54598796,
       100.41593106,  98.83657062,  80.79830374, 112.76446008,
       102.1401337 ,  81.51697096, 103.57603558, 103.05576265,
       116.24753976,  95.71960412, 104.95560273,  92.90084925,
        94.22811375,  85.90441826,  81.26477801,  73.35449148,
       105.94865967,  98.9599328 , 109.77465153, 104.8179181 ,
       106.06278426,  84.92215178, 106.8712541 ,  85.54708217,
        73.90286397,  94.09344682, 106.95243678,  85.22024184,
        98.63830525,  53.70470234, 102.9432461 , 103.53616341,
       103.02199488, 104.57833138, 103.4402746 , 113.85084947,
       128.63363848,  90.03477333, 116.90284015,  98.48853948,
       113.18443745,  91.36517895, 132.58921651,  74.0767534 ,
       112.85587411, 128.96149295,  97.95822941, 126.16679044,
       109.81329176, 115.4988061 ,  71.80155674,  98.85160775,
        89.17613611,  97.81422482,  82.37173106, 113.31915238,
       142.02089065, 103.28195347, 107.6657585 , 106.97125269,
       106.39451589, 116.53179541,  90.10510878, 105.91339428,
        93.18033617, 103.70995945,  91.58966262,  80.43944709,
        93.54345494, 111.23926751,  89.00852109, 110.73845003,
        90.12555112,  96.18176717,  78.24277035,  87.98641164,
       119.64692501,  98.64739478, 111.63761834, 104.47335789,
        93.03034643,  65.75462089,  93.62150619,  91.88402601,
       107.66336836,  96.31365911,  96.23739283, 112.70845104,
       116.38392107, 121.96713381,  98.03046184,  92.62971004,
        72.65469814,  75.96678775, 115.40813555, 113.58350774,
        69.9990584 ,  91.09511353, 103.11339027,  94.02507355,
       117.0592409 , 119.3527782 ,  99.00970381,  96.83025249,
        98.66390507, 105.26988256, 101.84019679,  70.65537062,
       100.68141432,  93.25061583,  87.05068809,  96.70907704,
       116.0392265 ,  82.17983281, 112.88436948, 119.36391972,
       103.95890588, 109.38193355,  99.89555131,  86.99307111,
       100.47861706, 113.90876413, 107.856773  ,  64.7045293 ,
       106.25544696,  84.20159338, 107.82198094, 111.63049779,
       105.31563909, 116.60405399, 103.00617833, 104.23317226,
       100.44292748, 106.29450738, 118.98908313, 103.34780323,
       105.28716758, 103.23959772, 104.4068964 , 106.05520597,
        95.62626145,  99.74774474,  72.87259358, 123.23701681,
        77.02536045,  69.16252729, 102.02310075,  69.46382028,
        94.64862897, 102.29160763, 109.42801534,  87.97302002,
       111.33759701, 103.29403801,  85.62749158,  97.9237882 ,
       110.28581651,  90.61511646,  89.48255022,  72.26866732,
       103.70520289,  93.59525296,  98.31463056, 107.07756203,
       112.81485596, 130.52331802,  82.09651242,  96.28664259,
       124.37951538, 117.91872093,  92.31831248,  98.25216686,
        95.45052015, 100.04643087, 110.39220819,  71.02367006,
       105.62559041,  89.99742759,  97.02301084,  93.53390331,
        84.88493438, 123.93189095, 107.35472813,  97.70458279,
        95.01108043,  99.209158  ,  94.43859015, 124.47448482,
        80.68555234, 118.77815065, 103.93756924,  99.24386134,
        79.0867819 ,  99.70606451, 111.95446039, 123.56715096,
        95.64674676,  86.79906111,  90.79214286,  98.65070313,
       117.5730887 ,  84.36723584,  89.63619916, 114.25325542,
       110.06611456,  89.32838208, 120.49844008,  86.87466791,
       113.44861062,  83.86132142,  64.73560474, 103.53527575,
       114.37354034, 102.2665573 , 115.3229163 ,  88.70980774,
       125.98375472,  92.95484368, 115.0909738 ,  81.82536307,
        89.64589678, 118.60067294,  82.38834691, 100.04892664,
       116.27525431, 109.68377124,  95.81738884,  98.90862493,
       101.27556979,  90.55944232, 103.33259658, 112.57264416,
       142.68392321,  87.11083944,  82.39479631, 105.98477246,
       122.24882424, 106.32376577,  70.60019752,  95.88749092,
        97.87170732,  87.37340662,  93.20638414, 100.50699107,
        63.35570678,  78.64169657, 113.32150198,  77.29230813,
       120.19524739, 117.18844799,  53.86765939,  86.16184564,
       108.82623894,  82.2441102 , 108.74467262,  96.57274862,
       110.34944659,  99.79582579,  89.32828344, 100.50555945,
       105.18420186,  88.45597833,  96.50763053,  93.854318  ,
       122.59112725,  97.63941608, 113.57117195, 115.12632946,
        98.04762058, 106.81259324, 109.17688153,  94.87463404,
       121.12240808,  72.46343655,  99.13288651, 123.91847755,
       108.0056549 ,  96.96784536, 105.39561758,  69.40178451,
       106.97725478,  93.90962327, 134.45144945,  93.7996464 ,
       111.86563645,  94.63647796,  95.8993193 ,  96.02550127,
       109.44775628,  95.46268326, 108.7937723 ,  91.45985755,
       110.45595974,  89.37419214, 105.20841586,  73.6453754 ,
       107.32778543,  85.59381048,  99.85056133,  66.24776581,
       122.47010753, 111.52156612,  86.48359045, 102.17059529,
       104.10749087,  84.70640748,  72.83770097, 115.53554606,
        92.20502397,  71.49664808,  71.65801846, 112.09816279,
       105.45620345,  95.18911865, 141.28702989, 108.31481415,
       124.08894854, 101.01124981,  99.21394594,  91.00799595,
        89.16350127,  88.62583936, 102.89617386,  97.79823471,
       101.20380447,  95.02042538, 115.97321819, 106.30403105,
        88.28523891,  95.70775193,  96.13124883, 106.67402741,
       117.22930533,  87.49831197,  84.59609602,  98.81732834,
        84.10788134, 102.88419661,  92.20733031,  85.42636899,
       101.33039797, 113.37348521, 104.74941115,  92.11985943,
       121.63271747,  98.84755372, 106.15796453,  96.39714502,
        95.33603967,  90.50919022,  98.85405938, 107.5819793 ,
       101.05529368,  94.93068548, 107.16581779, 105.61389948,
        81.98642443,  84.15650537, 110.91143033, 101.12542953,
       106.12930407,  98.88912614, 108.82204217, 108.69315645,
       100.25668008,  95.93866264, 117.62651372, 102.60903911,
        76.13576192, 104.23970378,  85.16002475,  97.18174129,
       102.22980884, 125.17383168,  86.92199812,  77.23064712,
       110.07999327,  74.77039617,  89.01455248, 111.34732635,
        92.40539416, 107.81531094, 102.65683863,  76.20786511,
        89.69041344, 105.39145485,  80.44845189, 119.49354607,
        89.63444412,  94.11898379,  94.75079178,  85.46039947,
       106.5739846 , 107.40911075, 117.15313236, 121.43063871,
        92.22184904, 119.95753734,  80.80464151, 112.34307554,
       128.36340566,  95.48786154, 133.75923585, 101.70064927,
       142.17031598,  97.71969496, 100.10498761, 104.96218896,
       107.27640274, 128.56296714, 125.09342871, 105.3092429 ,
       106.15758898,  78.33576815,  91.36427776,  83.31860692,
       142.72097008,  97.67880587, 126.58316126,  83.85167586,
       113.85516473, 107.66687807, 107.41480642,  77.96579103,
        87.96948758,  70.1459826 , 118.70468021,  97.54752049,
       105.65549569,  97.62154031,  80.97502495,  95.05685844,
        92.5780929 , 103.13709909, 119.19026606, 110.52072069,
        94.1150611 ,  88.3463202 ,  61.38689845, 115.8919121 ,
       120.39396063,  87.08736566,  99.08520088,  96.39102124,
        99.19999433, 116.71886639, 111.09405163,  77.13317446,
       121.10926449, 111.95478476,  94.14937488,  78.29883761,
       115.41075569, 120.68923941,  81.32608826, 123.63016413,
        85.15716607, 109.84682347, 127.20824347, 118.04177539,
        90.50342455, 110.76454564, 100.51098513,  99.2751872 ,
       113.04377762, 111.78562657,  77.29768478, 100.89133552,
        96.83262966, 102.8235686 ,  76.99649372, 114.98469941,
       110.98488108, 113.6407157 , 114.63599642,  93.92813487,
       115.18520465,  82.30935314,  93.24582299, 103.52750738,
       101.01944334,  83.62322462,  77.34414882,  94.82323505,
       102.98516376, 113.24662325,  86.76418753,  98.66551167,
       116.4460468 ,  98.58495463, 110.14953054, 118.89961344,
        95.95154408, 108.1998893 ,  81.90709671,  99.00878086,
       126.01217676,  87.08717677, 105.67063485,  98.28646341,
        88.5102649 ,  78.92950073,  91.86877476,  97.44473735,
        92.39869296,  95.61733127,  95.55248748, 117.11101866,
       126.17049865, 108.3559398 , 106.92853016, 112.63563817,
       111.86820294, 103.09989868,  84.32340815,  82.30419345,
       121.83359912, 100.29757271, 113.14313541,  85.89453844,
        93.50376346,  82.98655793,  89.9569088 , 121.89290947,
       107.65014981,  83.11405153,  96.79597131, 107.74469735,
       104.81731945,  87.7780023 , 120.30174671,  96.36968595,
       101.51679475, 109.15413069, 120.98225857, 115.97444279,
        80.81374901,  97.69161943, 115.02497992,  84.39081126,
       104.16664036,  86.32605048,  86.03448707, 111.41154833,
       134.06955642,  96.99502512, 120.19779761,  96.00141224,
        84.67380185,  93.62641204,  78.42815764,  96.99481872,
       132.31733745,  73.45401052,  72.01582876, 105.38875314,
       125.27462951, 111.18743854, 106.42186803,  84.30081656,
       100.59624983,  55.540855  , 113.34172975, 103.4959151 ,
        88.43513138,  93.5207413 , 122.1552139 , 105.09270981,
        98.00644201,  95.63001173,  98.09703131, 102.96006471,
       110.50465947,  90.70294305,  92.72386778, 122.6446899 ,
       119.98371836,  89.3141778 ,  74.53918054, 115.79744386,
        78.38985637, 103.28150274, 109.73544412,  96.46878748,
       100.33264041, 131.63731055,  91.72933933, 135.67842398,
        93.20156909,  93.66947756, 103.63901978, 102.5814303 ,
       108.308195  , 102.32378803, 113.14120297,  85.17683258,
        89.2348923 , 122.54952803,  79.37568944, 110.16700177,
       109.79990084,  99.82975539,  98.5310778 ,  88.86597377,
        97.21900642,  90.49632245, 115.73670449,  89.0602972 ,
       102.6219185 , 106.52096671, 103.24208395,  76.07069322,
       121.63008882,  91.22960994,  95.07095379,  66.4065022 ,
       117.13272248,  86.77911999,  70.21012838, 119.96189397,
       127.66994052, 101.80203745,  86.3059876 ,  98.05156781,
       133.335983  , 100.78900051, 100.58020353,  89.49012723,
       100.92192334, 109.5593863 ,  82.09800446,  94.1059548 ,
        62.75041661,  96.3596361 ,  83.74313027,  69.91076725,
       109.09429526,  81.03332762,  87.08907611,  95.36902438,
       110.10957984, 108.01011101,  81.65361255,  88.07961156,
        90.26884943, 100.67403719, 116.0719161 ,  86.83465295])

Compute the **mean**, **median**, and **mode**

In [3]:
from scipy import stats
mean = samples.mean()
median = np.median(samples)
mode= stats.mode(samples)



print("Mean: ", mean)
print("Median: ", median)
print("Mode: ", mode)

Mean:  99.98403329900586
Median:  99.81279058935331
Mode:  ModeResult(mode=array([53.70470234]), count=array([1]))

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [4]:
min = samples.min()
max = samples.max()
q1 = np.quantile(samples, 0.25)
q3 = np.quantile(samples, 0.75)
iqr = q3 - q1 

print("Min: ", min)
print("Max: ", max)
print("Q1: ", q1)
print("Q3: ", q3)
print("iqr ", iqr)

Min:  53.70470233863507
Max:  142.7209700790326
Q1:  90.43945419100623
Q3:  109.86848692586221
iqr  19.42903273485598

Compute the **variance** and **standard deviation**

In [23]:
stats.tvar(samples)

219.56734332306536

In [5]:
df1 = pd.DataFrame(samples)

variance = df1.var()

st_dev = df1.std()

print("Variance:", variance)
print("Standard Deviation:", st_dev)

Variance: 0    219.567343
dtype: float64
Standard Deviation: 0    14.817805
dtype: float64

Compute the **skewness** and **kurtosis**

In [24]:
stats.skew(samples)

-0.058200927324763375

In [25]:
stats.kurtosis(samples)

0.059544494113888735

In [27]:
skewness = df1.skew()
kurtosis = df1.kurtosis()

print("Skewness:", skewness)
print("Kurtosis:", kurtosis)

Skewness: 0   -0.058288
dtype: float64
Kurtosis: 0    0.065867
dtype: float64

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [8]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [9]:
y = np.array([1,2,3,4,5,6,7,8,9,10])
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [10]:
r = np.corrcoef(x, y)
r

array([[1., 1.],
       [1., 1.]])

## Pandas Correlation Calculation

Run the code below

In [16]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [17]:
r, p = stats.pearsonr(x, y)
r

0.7586402890911869

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [20]:
rho = stats.spearmanr(x, y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [28]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [29]:
tips = sns.load_dataset("tips")

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [30]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [31]:
tips.corr(method = "pearson")

            total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000